### ISSUE TITLE
Incompatible with Oculus

### ISSUE THREAD

**Issue by niraqw15** [nanite/Literal-Sky-Block#3]
### Mod version

literal-sky-block-1802.1.3-build.4

### Forge mod loader version

40.1.84

### Repeatable?

- [X] Yes

### Link to log files

Please link to crashes in the future 

### Description of the issue you are having

The game crashes upon loading any world, even a new one, when Literal Sky Block and Oculus are present. Everything is fine when only Literal Sky Block and Rubidium are present.

Mods:
literal-sky-block-1802.1.3-build.4
oculus-mc1.18.2-1.2.5a
rubidium-0.5.4

### Information

- [X] I have provided as much information as possible

**Comment by Karma-Fox** [comment]
Has also been posted in Asek3/Oculus#205. Linking this so this issue is tracked in both Repos.

**Comment by MichaelHillcox** [comment]
We're aware of this bug and looking into possible solutions. This is an incompatibility between forge, oculus and our mod.

**Comment by SheroxGG** [comment]
Same issue, hope this could be fixed soon! Thanks a lot for your work!

**Comment by Gaming32** [comment]
I fixed this in my Fabric port: https://github.com/Gaming32/literal-sky-block-fabric/commit/f14c82f3ef7f8e86bccde134ad847d83f8bd8d69. If you want to pull those changes in, that would be great.

**Comment by ImChinaNB** [comment]
Is incompatiblility completely resolved?
Playing with latest build `literal-sky-block-1802.1.3-build.5` with Rubidium + Oculus, my game didn't crash. But if I turned the shaders on, the world became pure black/white. Shaders work fine after removing literal-sky.

**Comment by Gaming32** [comment]
Yeah, that's fixed in the commit after the one that was pulled in.

**Comment by Gaming32** [comment]
This should fix it: https://github.com/Gaming32/literal-sky-block-fabric/commit/710c97e1bad898d94d5fae7d188eb8f94f18cc5b

**Comment by StarskyXIII** [comment]
Sorry, it seems latest version still not actually fix compatible issue.
With Literal Sky Block, any shaderpack will be broken.
Without Literal Sky Block, shaders will works fine.

With Literal Sky Block
![2022-12-23_00 53 41](https://user-images.githubusercontent.com/71606873/209186310-c02f7fb5-4a4a-4a20-ba82-1b94b453986d.png)

Without Literal Sky Block
![2022-12-23_00 45 16](https://user-images.githubusercontent.com/71606873/209185698-86d76068-8c68-4e3a-9fc4-41f313da5572.png)

**Comment by Garulf** [comment]
Crashing is gone (which is great!) but can confirm that the game is unplayable if any shaders are active.

**Comment by greensad** [comment]
This is still busted and should be high priority as oculus shaders and Literal Sky Block are both important mods for the best Stoneblock 3 experience. When loading a shader the world is a flat colour and nothing is visible in most shaders, in some shaders lights are very dimly visible but it isn't playable and in others the skybox is rendered.

**Comment by shikyo13** [comment]
This is not fixed as far as I can tell. Why is this issue closed?

**Comment by Draylynn** [comment]
Whilst nearly every shader I've tried has shows a heavily black or white screen with this issue... The "Bliss | An Edit of Chocapic13's Shaders" is _mostly_ functional and doesn't appear to black/whiteout. I don't know if that helps offer any clues to resolving the problem based on how this particular shader works.

**Comment by Snoddas76** [comment]
Has there been any kind of progress on this issue?

**Comment by Wand7940** [comment]
Any updates

**Comment by NaviFaeGirl** [comment]
As far as I can tell... Still very broken right now. Everything becomes entirely foggy white with shaders on and UI goes invisible while this mod is also installed. For me it hasn't changed no matter what shaders I use, I saw someone else here suggested the Bliss shaders for being still funky but not completely broken but even those broke for me.

I'm playing with Oculus if that makes any difference. Sodium/Embeddium/Chloride instead of Rubidium (since that breaks everything for me even worse if i use that). 1.18.2 forge, mainly complimentary shaders + the Euphoria patch mod for them
